[profile.default]
solc = "0.8.30"
auto_detect_solc = false
evm_version = "prague"
src = "src"
script = "script"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true

# Disable metadata hash for deterministic bytecode
bytecode_hash = "none"
cbor_metadata = false

extra_output = ["storageLayout"]
fs_permissions = [
  { access='read', path='./configs' },
  { access='read', path='./test' },
  { access='read', path='./out' },
  { access='write', path='./deployment.json' },
  { access='write', path='./deployment-mailbox-l2.json' },
  { access='write', path='./deployment-mailbox-l1.json' }
]

[rpc_endpoints]
"sepolia" = "${SEPOLIA_RPC_URL}"
"sepolia/op" = "https://sepolia.optimism.io"
"sepolia/worldchain" = "https://worldchain-sepolia.g.alchemy.com/public"
"sepolia/unichain" = "https://sepolia.unichain.org"
"sepolia/base" = "https://sepolia.base.org"
 
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
